name: tgortc_example
description: "TgoRTC Flutter SDK Example App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  tgortcflutter:
    path: ../
  cupertino_icons: ^1.0.5
  permission_handler: ^10.4.0
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  flutter_webrtc:
    git:
      url: "https://gitcode.com/openharmony-sig/fluttertpc_flutter_webrtc.git"
  livekit_client:
    git:
      url: "https://gitcode.com/openharmony-sig/fluttertpc_livekit_client.git"
  meta: 1.8.0
  collection: 1.17.0